
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AnnouncementFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AnnouncementFile
 * 
 */
export type AnnouncementFileModel = runtime.Types.Result.DefaultSelection<Prisma.$AnnouncementFilePayload>

export type AggregateAnnouncementFile = {
  _count: AnnouncementFileCountAggregateOutputType | null
  _avg: AnnouncementFileAvgAggregateOutputType | null
  _sum: AnnouncementFileSumAggregateOutputType | null
  _min: AnnouncementFileMinAggregateOutputType | null
  _max: AnnouncementFileMaxAggregateOutputType | null
}

export type AnnouncementFileAvgAggregateOutputType = {
  id: number | null
  announcementId: number | null
  fileSize: number | null
}

export type AnnouncementFileSumAggregateOutputType = {
  id: number | null
  announcementId: number | null
  fileSize: number | null
}

export type AnnouncementFileMinAggregateOutputType = {
  id: number | null
  announcementId: number | null
  fileKey: string | null
  fileName: string | null
  fileSize: number | null
  mimeType: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AnnouncementFileMaxAggregateOutputType = {
  id: number | null
  announcementId: number | null
  fileKey: string | null
  fileName: string | null
  fileSize: number | null
  mimeType: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AnnouncementFileCountAggregateOutputType = {
  id: number
  announcementId: number
  fileKey: number
  fileName: number
  fileSize: number
  mimeType: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AnnouncementFileAvgAggregateInputType = {
  id?: true
  announcementId?: true
  fileSize?: true
}

export type AnnouncementFileSumAggregateInputType = {
  id?: true
  announcementId?: true
  fileSize?: true
}

export type AnnouncementFileMinAggregateInputType = {
  id?: true
  announcementId?: true
  fileKey?: true
  fileName?: true
  fileSize?: true
  mimeType?: true
  createdAt?: true
  updatedAt?: true
}

export type AnnouncementFileMaxAggregateInputType = {
  id?: true
  announcementId?: true
  fileKey?: true
  fileName?: true
  fileSize?: true
  mimeType?: true
  createdAt?: true
  updatedAt?: true
}

export type AnnouncementFileCountAggregateInputType = {
  id?: true
  announcementId?: true
  fileKey?: true
  fileName?: true
  fileSize?: true
  mimeType?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AnnouncementFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnnouncementFile to aggregate.
   */
  where?: Prisma.AnnouncementFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnnouncementFiles to fetch.
   */
  orderBy?: Prisma.AnnouncementFileOrderByWithRelationInput | Prisma.AnnouncementFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AnnouncementFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnnouncementFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnnouncementFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AnnouncementFiles
  **/
  _count?: true | AnnouncementFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AnnouncementFileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AnnouncementFileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AnnouncementFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AnnouncementFileMaxAggregateInputType
}

export type GetAnnouncementFileAggregateType<T extends AnnouncementFileAggregateArgs> = {
      [P in keyof T & keyof AggregateAnnouncementFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAnnouncementFile[P]>
    : Prisma.GetScalarType<T[P], AggregateAnnouncementFile[P]>
}




export type AnnouncementFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnnouncementFileWhereInput
  orderBy?: Prisma.AnnouncementFileOrderByWithAggregationInput | Prisma.AnnouncementFileOrderByWithAggregationInput[]
  by: Prisma.AnnouncementFileScalarFieldEnum[] | Prisma.AnnouncementFileScalarFieldEnum
  having?: Prisma.AnnouncementFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AnnouncementFileCountAggregateInputType | true
  _avg?: AnnouncementFileAvgAggregateInputType
  _sum?: AnnouncementFileSumAggregateInputType
  _min?: AnnouncementFileMinAggregateInputType
  _max?: AnnouncementFileMaxAggregateInputType
}

export type AnnouncementFileGroupByOutputType = {
  id: number
  announcementId: number
  fileKey: string
  fileName: string
  fileSize: number | null
  mimeType: string | null
  createdAt: Date
  updatedAt: Date
  _count: AnnouncementFileCountAggregateOutputType | null
  _avg: AnnouncementFileAvgAggregateOutputType | null
  _sum: AnnouncementFileSumAggregateOutputType | null
  _min: AnnouncementFileMinAggregateOutputType | null
  _max: AnnouncementFileMaxAggregateOutputType | null
}

type GetAnnouncementFileGroupByPayload<T extends AnnouncementFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AnnouncementFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AnnouncementFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AnnouncementFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AnnouncementFileGroupByOutputType[P]>
      }
    >
  >



export type AnnouncementFileWhereInput = {
  AND?: Prisma.AnnouncementFileWhereInput | Prisma.AnnouncementFileWhereInput[]
  OR?: Prisma.AnnouncementFileWhereInput[]
  NOT?: Prisma.AnnouncementFileWhereInput | Prisma.AnnouncementFileWhereInput[]
  id?: Prisma.IntFilter<"AnnouncementFile"> | number
  announcementId?: Prisma.IntFilter<"AnnouncementFile"> | number
  fileKey?: Prisma.StringFilter<"AnnouncementFile"> | string
  fileName?: Prisma.StringFilter<"AnnouncementFile"> | string
  fileSize?: Prisma.IntNullableFilter<"AnnouncementFile"> | number | null
  mimeType?: Prisma.StringNullableFilter<"AnnouncementFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AnnouncementFile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AnnouncementFile"> | Date | string
  announcement?: Prisma.XOR<Prisma.AnnouncementScalarRelationFilter, Prisma.AnnouncementWhereInput>
}

export type AnnouncementFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  announcement?: Prisma.AnnouncementOrderByWithRelationInput
  _relevance?: Prisma.AnnouncementFileOrderByRelevanceInput
}

export type AnnouncementFileWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AnnouncementFileWhereInput | Prisma.AnnouncementFileWhereInput[]
  OR?: Prisma.AnnouncementFileWhereInput[]
  NOT?: Prisma.AnnouncementFileWhereInput | Prisma.AnnouncementFileWhereInput[]
  announcementId?: Prisma.IntFilter<"AnnouncementFile"> | number
  fileKey?: Prisma.StringFilter<"AnnouncementFile"> | string
  fileName?: Prisma.StringFilter<"AnnouncementFile"> | string
  fileSize?: Prisma.IntNullableFilter<"AnnouncementFile"> | number | null
  mimeType?: Prisma.StringNullableFilter<"AnnouncementFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AnnouncementFile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AnnouncementFile"> | Date | string
  announcement?: Prisma.XOR<Prisma.AnnouncementScalarRelationFilter, Prisma.AnnouncementWhereInput>
}, "id">

export type AnnouncementFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AnnouncementFileCountOrderByAggregateInput
  _avg?: Prisma.AnnouncementFileAvgOrderByAggregateInput
  _max?: Prisma.AnnouncementFileMaxOrderByAggregateInput
  _min?: Prisma.AnnouncementFileMinOrderByAggregateInput
  _sum?: Prisma.AnnouncementFileSumOrderByAggregateInput
}

export type AnnouncementFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.AnnouncementFileScalarWhereWithAggregatesInput | Prisma.AnnouncementFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.AnnouncementFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AnnouncementFileScalarWhereWithAggregatesInput | Prisma.AnnouncementFileScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AnnouncementFile"> | number
  announcementId?: Prisma.IntWithAggregatesFilter<"AnnouncementFile"> | number
  fileKey?: Prisma.StringWithAggregatesFilter<"AnnouncementFile"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"AnnouncementFile"> | string
  fileSize?: Prisma.IntNullableWithAggregatesFilter<"AnnouncementFile"> | number | null
  mimeType?: Prisma.StringNullableWithAggregatesFilter<"AnnouncementFile"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AnnouncementFile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AnnouncementFile"> | Date | string
}

export type AnnouncementFileCreateInput = {
  fileKey: string
  fileName: string
  fileSize?: number | null
  mimeType?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  announcement: Prisma.AnnouncementCreateNestedOneWithoutFilesInput
}

export type AnnouncementFileUncheckedCreateInput = {
  id?: number
  announcementId: number
  fileKey: string
  fileName: string
  fileSize?: number | null
  mimeType?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnnouncementFileUpdateInput = {
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  announcement?: Prisma.AnnouncementUpdateOneRequiredWithoutFilesNestedInput
}

export type AnnouncementFileUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  announcementId?: Prisma.IntFieldUpdateOperationsInput | number
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnnouncementFileCreateManyInput = {
  id?: number
  announcementId: number
  fileKey: string
  fileName: string
  fileSize?: number | null
  mimeType?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnnouncementFileUpdateManyMutationInput = {
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnnouncementFileUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  announcementId?: Prisma.IntFieldUpdateOperationsInput | number
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnnouncementFileListRelationFilter = {
  every?: Prisma.AnnouncementFileWhereInput
  some?: Prisma.AnnouncementFileWhereInput
  none?: Prisma.AnnouncementFileWhereInput
}

export type AnnouncementFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AnnouncementFileOrderByRelevanceInput = {
  fields: Prisma.AnnouncementFileOrderByRelevanceFieldEnum | Prisma.AnnouncementFileOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AnnouncementFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AnnouncementFileAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
}

export type AnnouncementFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AnnouncementFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AnnouncementFileSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  announcementId?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
}

export type AnnouncementFileCreateNestedManyWithoutAnnouncementInput = {
  create?: Prisma.XOR<Prisma.AnnouncementFileCreateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput> | Prisma.AnnouncementFileCreateWithoutAnnouncementInput[] | Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput[]
  connectOrCreate?: Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput | Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput[]
  createMany?: Prisma.AnnouncementFileCreateManyAnnouncementInputEnvelope
  connect?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
}

export type AnnouncementFileUncheckedCreateNestedManyWithoutAnnouncementInput = {
  create?: Prisma.XOR<Prisma.AnnouncementFileCreateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput> | Prisma.AnnouncementFileCreateWithoutAnnouncementInput[] | Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput[]
  connectOrCreate?: Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput | Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput[]
  createMany?: Prisma.AnnouncementFileCreateManyAnnouncementInputEnvelope
  connect?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
}

export type AnnouncementFileUpdateManyWithoutAnnouncementNestedInput = {
  create?: Prisma.XOR<Prisma.AnnouncementFileCreateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput> | Prisma.AnnouncementFileCreateWithoutAnnouncementInput[] | Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput[]
  connectOrCreate?: Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput | Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput[]
  upsert?: Prisma.AnnouncementFileUpsertWithWhereUniqueWithoutAnnouncementInput | Prisma.AnnouncementFileUpsertWithWhereUniqueWithoutAnnouncementInput[]
  createMany?: Prisma.AnnouncementFileCreateManyAnnouncementInputEnvelope
  set?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  disconnect?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  delete?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  connect?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  update?: Prisma.AnnouncementFileUpdateWithWhereUniqueWithoutAnnouncementInput | Prisma.AnnouncementFileUpdateWithWhereUniqueWithoutAnnouncementInput[]
  updateMany?: Prisma.AnnouncementFileUpdateManyWithWhereWithoutAnnouncementInput | Prisma.AnnouncementFileUpdateManyWithWhereWithoutAnnouncementInput[]
  deleteMany?: Prisma.AnnouncementFileScalarWhereInput | Prisma.AnnouncementFileScalarWhereInput[]
}

export type AnnouncementFileUncheckedUpdateManyWithoutAnnouncementNestedInput = {
  create?: Prisma.XOR<Prisma.AnnouncementFileCreateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput> | Prisma.AnnouncementFileCreateWithoutAnnouncementInput[] | Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput[]
  connectOrCreate?: Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput | Prisma.AnnouncementFileCreateOrConnectWithoutAnnouncementInput[]
  upsert?: Prisma.AnnouncementFileUpsertWithWhereUniqueWithoutAnnouncementInput | Prisma.AnnouncementFileUpsertWithWhereUniqueWithoutAnnouncementInput[]
  createMany?: Prisma.AnnouncementFileCreateManyAnnouncementInputEnvelope
  set?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  disconnect?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  delete?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  connect?: Prisma.AnnouncementFileWhereUniqueInput | Prisma.AnnouncementFileWhereUniqueInput[]
  update?: Prisma.AnnouncementFileUpdateWithWhereUniqueWithoutAnnouncementInput | Prisma.AnnouncementFileUpdateWithWhereUniqueWithoutAnnouncementInput[]
  updateMany?: Prisma.AnnouncementFileUpdateManyWithWhereWithoutAnnouncementInput | Prisma.AnnouncementFileUpdateManyWithWhereWithoutAnnouncementInput[]
  deleteMany?: Prisma.AnnouncementFileScalarWhereInput | Prisma.AnnouncementFileScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type AnnouncementFileCreateWithoutAnnouncementInput = {
  fileKey: string
  fileName: string
  fileSize?: number | null
  mimeType?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnnouncementFileUncheckedCreateWithoutAnnouncementInput = {
  id?: number
  fileKey: string
  fileName: string
  fileSize?: number | null
  mimeType?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnnouncementFileCreateOrConnectWithoutAnnouncementInput = {
  where: Prisma.AnnouncementFileWhereUniqueInput
  create: Prisma.XOR<Prisma.AnnouncementFileCreateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput>
}

export type AnnouncementFileCreateManyAnnouncementInputEnvelope = {
  data: Prisma.AnnouncementFileCreateManyAnnouncementInput | Prisma.AnnouncementFileCreateManyAnnouncementInput[]
  skipDuplicates?: boolean
}

export type AnnouncementFileUpsertWithWhereUniqueWithoutAnnouncementInput = {
  where: Prisma.AnnouncementFileWhereUniqueInput
  update: Prisma.XOR<Prisma.AnnouncementFileUpdateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedUpdateWithoutAnnouncementInput>
  create: Prisma.XOR<Prisma.AnnouncementFileCreateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedCreateWithoutAnnouncementInput>
}

export type AnnouncementFileUpdateWithWhereUniqueWithoutAnnouncementInput = {
  where: Prisma.AnnouncementFileWhereUniqueInput
  data: Prisma.XOR<Prisma.AnnouncementFileUpdateWithoutAnnouncementInput, Prisma.AnnouncementFileUncheckedUpdateWithoutAnnouncementInput>
}

export type AnnouncementFileUpdateManyWithWhereWithoutAnnouncementInput = {
  where: Prisma.AnnouncementFileScalarWhereInput
  data: Prisma.XOR<Prisma.AnnouncementFileUpdateManyMutationInput, Prisma.AnnouncementFileUncheckedUpdateManyWithoutAnnouncementInput>
}

export type AnnouncementFileScalarWhereInput = {
  AND?: Prisma.AnnouncementFileScalarWhereInput | Prisma.AnnouncementFileScalarWhereInput[]
  OR?: Prisma.AnnouncementFileScalarWhereInput[]
  NOT?: Prisma.AnnouncementFileScalarWhereInput | Prisma.AnnouncementFileScalarWhereInput[]
  id?: Prisma.IntFilter<"AnnouncementFile"> | number
  announcementId?: Prisma.IntFilter<"AnnouncementFile"> | number
  fileKey?: Prisma.StringFilter<"AnnouncementFile"> | string
  fileName?: Prisma.StringFilter<"AnnouncementFile"> | string
  fileSize?: Prisma.IntNullableFilter<"AnnouncementFile"> | number | null
  mimeType?: Prisma.StringNullableFilter<"AnnouncementFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AnnouncementFile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AnnouncementFile"> | Date | string
}

export type AnnouncementFileCreateManyAnnouncementInput = {
  id?: number
  fileKey: string
  fileName: string
  fileSize?: number | null
  mimeType?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnnouncementFileUpdateWithoutAnnouncementInput = {
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnnouncementFileUncheckedUpdateWithoutAnnouncementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnnouncementFileUncheckedUpdateManyWithoutAnnouncementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fileKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AnnouncementFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  announcementId?: boolean
  fileKey?: boolean
  fileName?: boolean
  fileSize?: boolean
  mimeType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  announcement?: boolean | Prisma.AnnouncementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["announcementFile"]>



export type AnnouncementFileSelectScalar = {
  id?: boolean
  announcementId?: boolean
  fileKey?: boolean
  fileName?: boolean
  fileSize?: boolean
  mimeType?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AnnouncementFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "announcementId" | "fileKey" | "fileName" | "fileSize" | "mimeType" | "createdAt" | "updatedAt", ExtArgs["result"]["announcementFile"]>
export type AnnouncementFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  announcement?: boolean | Prisma.AnnouncementDefaultArgs<ExtArgs>
}

export type $AnnouncementFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AnnouncementFile"
  objects: {
    announcement: Prisma.$AnnouncementPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    announcementId: number
    fileKey: string
    fileName: string
    fileSize: number | null
    mimeType: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["announcementFile"]>
  composites: {}
}

export type AnnouncementFileGetPayload<S extends boolean | null | undefined | AnnouncementFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload, S>

export type AnnouncementFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AnnouncementFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AnnouncementFileCountAggregateInputType | true
  }

export interface AnnouncementFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AnnouncementFile'], meta: { name: 'AnnouncementFile' } }
  /**
   * Find zero or one AnnouncementFile that matches the filter.
   * @param {AnnouncementFileFindUniqueArgs} args - Arguments to find a AnnouncementFile
   * @example
   * // Get one AnnouncementFile
   * const announcementFile = await prisma.announcementFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AnnouncementFileFindUniqueArgs>(args: Prisma.SelectSubset<T, AnnouncementFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AnnouncementFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AnnouncementFileFindUniqueOrThrowArgs} args - Arguments to find a AnnouncementFile
   * @example
   * // Get one AnnouncementFile
   * const announcementFile = await prisma.announcementFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AnnouncementFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AnnouncementFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnnouncementFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileFindFirstArgs} args - Arguments to find a AnnouncementFile
   * @example
   * // Get one AnnouncementFile
   * const announcementFile = await prisma.announcementFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AnnouncementFileFindFirstArgs>(args?: Prisma.SelectSubset<T, AnnouncementFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnnouncementFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileFindFirstOrThrowArgs} args - Arguments to find a AnnouncementFile
   * @example
   * // Get one AnnouncementFile
   * const announcementFile = await prisma.announcementFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AnnouncementFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AnnouncementFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AnnouncementFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AnnouncementFiles
   * const announcementFiles = await prisma.announcementFile.findMany()
   * 
   * // Get first 10 AnnouncementFiles
   * const announcementFiles = await prisma.announcementFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const announcementFileWithIdOnly = await prisma.announcementFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AnnouncementFileFindManyArgs>(args?: Prisma.SelectSubset<T, AnnouncementFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AnnouncementFile.
   * @param {AnnouncementFileCreateArgs} args - Arguments to create a AnnouncementFile.
   * @example
   * // Create one AnnouncementFile
   * const AnnouncementFile = await prisma.announcementFile.create({
   *   data: {
   *     // ... data to create a AnnouncementFile
   *   }
   * })
   * 
   */
  create<T extends AnnouncementFileCreateArgs>(args: Prisma.SelectSubset<T, AnnouncementFileCreateArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AnnouncementFiles.
   * @param {AnnouncementFileCreateManyArgs} args - Arguments to create many AnnouncementFiles.
   * @example
   * // Create many AnnouncementFiles
   * const announcementFile = await prisma.announcementFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AnnouncementFileCreateManyArgs>(args?: Prisma.SelectSubset<T, AnnouncementFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a AnnouncementFile.
   * @param {AnnouncementFileDeleteArgs} args - Arguments to delete one AnnouncementFile.
   * @example
   * // Delete one AnnouncementFile
   * const AnnouncementFile = await prisma.announcementFile.delete({
   *   where: {
   *     // ... filter to delete one AnnouncementFile
   *   }
   * })
   * 
   */
  delete<T extends AnnouncementFileDeleteArgs>(args: Prisma.SelectSubset<T, AnnouncementFileDeleteArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AnnouncementFile.
   * @param {AnnouncementFileUpdateArgs} args - Arguments to update one AnnouncementFile.
   * @example
   * // Update one AnnouncementFile
   * const announcementFile = await prisma.announcementFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AnnouncementFileUpdateArgs>(args: Prisma.SelectSubset<T, AnnouncementFileUpdateArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AnnouncementFiles.
   * @param {AnnouncementFileDeleteManyArgs} args - Arguments to filter AnnouncementFiles to delete.
   * @example
   * // Delete a few AnnouncementFiles
   * const { count } = await prisma.announcementFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AnnouncementFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, AnnouncementFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnnouncementFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AnnouncementFiles
   * const announcementFile = await prisma.announcementFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AnnouncementFileUpdateManyArgs>(args: Prisma.SelectSubset<T, AnnouncementFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one AnnouncementFile.
   * @param {AnnouncementFileUpsertArgs} args - Arguments to update or create a AnnouncementFile.
   * @example
   * // Update or create a AnnouncementFile
   * const announcementFile = await prisma.announcementFile.upsert({
   *   create: {
   *     // ... data to create a AnnouncementFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AnnouncementFile we want to update
   *   }
   * })
   */
  upsert<T extends AnnouncementFileUpsertArgs>(args: Prisma.SelectSubset<T, AnnouncementFileUpsertArgs<ExtArgs>>): Prisma.Prisma__AnnouncementFileClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AnnouncementFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileCountArgs} args - Arguments to filter AnnouncementFiles to count.
   * @example
   * // Count the number of AnnouncementFiles
   * const count = await prisma.announcementFile.count({
   *   where: {
   *     // ... the filter for the AnnouncementFiles we want to count
   *   }
   * })
  **/
  count<T extends AnnouncementFileCountArgs>(
    args?: Prisma.Subset<T, AnnouncementFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AnnouncementFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AnnouncementFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AnnouncementFileAggregateArgs>(args: Prisma.Subset<T, AnnouncementFileAggregateArgs>): Prisma.PrismaPromise<GetAnnouncementFileAggregateType<T>>

  /**
   * Group by AnnouncementFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnnouncementFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AnnouncementFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AnnouncementFileGroupByArgs['orderBy'] }
      : { orderBy?: AnnouncementFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AnnouncementFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAnnouncementFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AnnouncementFile model
 */
readonly fields: AnnouncementFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AnnouncementFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnnouncementFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  announcement<T extends Prisma.AnnouncementDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AnnouncementDefaultArgs<ExtArgs>>): Prisma.Prisma__AnnouncementClient<runtime.Types.Result.GetResult<Prisma.$AnnouncementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AnnouncementFile model
 */
export interface AnnouncementFileFieldRefs {
  readonly id: Prisma.FieldRef<"AnnouncementFile", 'Int'>
  readonly announcementId: Prisma.FieldRef<"AnnouncementFile", 'Int'>
  readonly fileKey: Prisma.FieldRef<"AnnouncementFile", 'String'>
  readonly fileName: Prisma.FieldRef<"AnnouncementFile", 'String'>
  readonly fileSize: Prisma.FieldRef<"AnnouncementFile", 'Int'>
  readonly mimeType: Prisma.FieldRef<"AnnouncementFile", 'String'>
  readonly createdAt: Prisma.FieldRef<"AnnouncementFile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AnnouncementFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AnnouncementFile findUnique
 */
export type AnnouncementFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * Filter, which AnnouncementFile to fetch.
   */
  where: Prisma.AnnouncementFileWhereUniqueInput
}

/**
 * AnnouncementFile findUniqueOrThrow
 */
export type AnnouncementFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * Filter, which AnnouncementFile to fetch.
   */
  where: Prisma.AnnouncementFileWhereUniqueInput
}

/**
 * AnnouncementFile findFirst
 */
export type AnnouncementFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * Filter, which AnnouncementFile to fetch.
   */
  where?: Prisma.AnnouncementFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnnouncementFiles to fetch.
   */
  orderBy?: Prisma.AnnouncementFileOrderByWithRelationInput | Prisma.AnnouncementFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnnouncementFiles.
   */
  cursor?: Prisma.AnnouncementFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnnouncementFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnnouncementFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnnouncementFiles.
   */
  distinct?: Prisma.AnnouncementFileScalarFieldEnum | Prisma.AnnouncementFileScalarFieldEnum[]
}

/**
 * AnnouncementFile findFirstOrThrow
 */
export type AnnouncementFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * Filter, which AnnouncementFile to fetch.
   */
  where?: Prisma.AnnouncementFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnnouncementFiles to fetch.
   */
  orderBy?: Prisma.AnnouncementFileOrderByWithRelationInput | Prisma.AnnouncementFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnnouncementFiles.
   */
  cursor?: Prisma.AnnouncementFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnnouncementFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnnouncementFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnnouncementFiles.
   */
  distinct?: Prisma.AnnouncementFileScalarFieldEnum | Prisma.AnnouncementFileScalarFieldEnum[]
}

/**
 * AnnouncementFile findMany
 */
export type AnnouncementFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * Filter, which AnnouncementFiles to fetch.
   */
  where?: Prisma.AnnouncementFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnnouncementFiles to fetch.
   */
  orderBy?: Prisma.AnnouncementFileOrderByWithRelationInput | Prisma.AnnouncementFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AnnouncementFiles.
   */
  cursor?: Prisma.AnnouncementFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnnouncementFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnnouncementFiles.
   */
  skip?: number
  distinct?: Prisma.AnnouncementFileScalarFieldEnum | Prisma.AnnouncementFileScalarFieldEnum[]
}

/**
 * AnnouncementFile create
 */
export type AnnouncementFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * The data needed to create a AnnouncementFile.
   */
  data: Prisma.XOR<Prisma.AnnouncementFileCreateInput, Prisma.AnnouncementFileUncheckedCreateInput>
}

/**
 * AnnouncementFile createMany
 */
export type AnnouncementFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AnnouncementFiles.
   */
  data: Prisma.AnnouncementFileCreateManyInput | Prisma.AnnouncementFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AnnouncementFile update
 */
export type AnnouncementFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * The data needed to update a AnnouncementFile.
   */
  data: Prisma.XOR<Prisma.AnnouncementFileUpdateInput, Prisma.AnnouncementFileUncheckedUpdateInput>
  /**
   * Choose, which AnnouncementFile to update.
   */
  where: Prisma.AnnouncementFileWhereUniqueInput
}

/**
 * AnnouncementFile updateMany
 */
export type AnnouncementFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AnnouncementFiles.
   */
  data: Prisma.XOR<Prisma.AnnouncementFileUpdateManyMutationInput, Prisma.AnnouncementFileUncheckedUpdateManyInput>
  /**
   * Filter which AnnouncementFiles to update
   */
  where?: Prisma.AnnouncementFileWhereInput
  /**
   * Limit how many AnnouncementFiles to update.
   */
  limit?: number
}

/**
 * AnnouncementFile upsert
 */
export type AnnouncementFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * The filter to search for the AnnouncementFile to update in case it exists.
   */
  where: Prisma.AnnouncementFileWhereUniqueInput
  /**
   * In case the AnnouncementFile found by the `where` argument doesn't exist, create a new AnnouncementFile with this data.
   */
  create: Prisma.XOR<Prisma.AnnouncementFileCreateInput, Prisma.AnnouncementFileUncheckedCreateInput>
  /**
   * In case the AnnouncementFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AnnouncementFileUpdateInput, Prisma.AnnouncementFileUncheckedUpdateInput>
}

/**
 * AnnouncementFile delete
 */
export type AnnouncementFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
  /**
   * Filter which AnnouncementFile to delete.
   */
  where: Prisma.AnnouncementFileWhereUniqueInput
}

/**
 * AnnouncementFile deleteMany
 */
export type AnnouncementFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnnouncementFiles to delete
   */
  where?: Prisma.AnnouncementFileWhereInput
  /**
   * Limit how many AnnouncementFiles to delete.
   */
  limit?: number
}

/**
 * AnnouncementFile without action
 */
export type AnnouncementFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnnouncementFile
   */
  select?: Prisma.AnnouncementFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnnouncementFile
   */
  omit?: Prisma.AnnouncementFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnnouncementFileInclude<ExtArgs> | null
}
