
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GalleryTextBlock` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GalleryTextBlock
 * 
 */
export type GalleryTextBlockModel = runtime.Types.Result.DefaultSelection<Prisma.$GalleryTextBlockPayload>

export type AggregateGalleryTextBlock = {
  _count: GalleryTextBlockCountAggregateOutputType | null
  _avg: GalleryTextBlockAvgAggregateOutputType | null
  _sum: GalleryTextBlockSumAggregateOutputType | null
  _min: GalleryTextBlockMinAggregateOutputType | null
  _max: GalleryTextBlockMaxAggregateOutputType | null
}

export type GalleryTextBlockAvgAggregateOutputType = {
  id: number | null
  postId: number | null
  order: number | null
}

export type GalleryTextBlockSumAggregateOutputType = {
  id: number | null
  postId: number | null
  order: number | null
}

export type GalleryTextBlockMinAggregateOutputType = {
  id: number | null
  postId: number | null
  content: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GalleryTextBlockMaxAggregateOutputType = {
  id: number | null
  postId: number | null
  content: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GalleryTextBlockCountAggregateOutputType = {
  id: number
  postId: number
  content: number
  order: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GalleryTextBlockAvgAggregateInputType = {
  id?: true
  postId?: true
  order?: true
}

export type GalleryTextBlockSumAggregateInputType = {
  id?: true
  postId?: true
  order?: true
}

export type GalleryTextBlockMinAggregateInputType = {
  id?: true
  postId?: true
  content?: true
  order?: true
  createdAt?: true
  updatedAt?: true
}

export type GalleryTextBlockMaxAggregateInputType = {
  id?: true
  postId?: true
  content?: true
  order?: true
  createdAt?: true
  updatedAt?: true
}

export type GalleryTextBlockCountAggregateInputType = {
  id?: true
  postId?: true
  content?: true
  order?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GalleryTextBlockAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GalleryTextBlock to aggregate.
   */
  where?: Prisma.GalleryTextBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryTextBlocks to fetch.
   */
  orderBy?: Prisma.GalleryTextBlockOrderByWithRelationInput | Prisma.GalleryTextBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GalleryTextBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryTextBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryTextBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GalleryTextBlocks
  **/
  _count?: true | GalleryTextBlockCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GalleryTextBlockAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GalleryTextBlockSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GalleryTextBlockMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GalleryTextBlockMaxAggregateInputType
}

export type GetGalleryTextBlockAggregateType<T extends GalleryTextBlockAggregateArgs> = {
      [P in keyof T & keyof AggregateGalleryTextBlock]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGalleryTextBlock[P]>
    : Prisma.GetScalarType<T[P], AggregateGalleryTextBlock[P]>
}




export type GalleryTextBlockGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GalleryTextBlockWhereInput
  orderBy?: Prisma.GalleryTextBlockOrderByWithAggregationInput | Prisma.GalleryTextBlockOrderByWithAggregationInput[]
  by: Prisma.GalleryTextBlockScalarFieldEnum[] | Prisma.GalleryTextBlockScalarFieldEnum
  having?: Prisma.GalleryTextBlockScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GalleryTextBlockCountAggregateInputType | true
  _avg?: GalleryTextBlockAvgAggregateInputType
  _sum?: GalleryTextBlockSumAggregateInputType
  _min?: GalleryTextBlockMinAggregateInputType
  _max?: GalleryTextBlockMaxAggregateInputType
}

export type GalleryTextBlockGroupByOutputType = {
  id: number
  postId: number
  content: string
  order: number
  createdAt: Date
  updatedAt: Date
  _count: GalleryTextBlockCountAggregateOutputType | null
  _avg: GalleryTextBlockAvgAggregateOutputType | null
  _sum: GalleryTextBlockSumAggregateOutputType | null
  _min: GalleryTextBlockMinAggregateOutputType | null
  _max: GalleryTextBlockMaxAggregateOutputType | null
}

type GetGalleryTextBlockGroupByPayload<T extends GalleryTextBlockGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GalleryTextBlockGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GalleryTextBlockGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GalleryTextBlockGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GalleryTextBlockGroupByOutputType[P]>
      }
    >
  >



export type GalleryTextBlockWhereInput = {
  AND?: Prisma.GalleryTextBlockWhereInput | Prisma.GalleryTextBlockWhereInput[]
  OR?: Prisma.GalleryTextBlockWhereInput[]
  NOT?: Prisma.GalleryTextBlockWhereInput | Prisma.GalleryTextBlockWhereInput[]
  id?: Prisma.IntFilter<"GalleryTextBlock"> | number
  postId?: Prisma.IntFilter<"GalleryTextBlock"> | number
  content?: Prisma.StringFilter<"GalleryTextBlock"> | string
  order?: Prisma.IntFilter<"GalleryTextBlock"> | number
  createdAt?: Prisma.DateTimeFilter<"GalleryTextBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GalleryTextBlock"> | Date | string
  post?: Prisma.XOR<Prisma.GalleryPostScalarRelationFilter, Prisma.GalleryPostWhereInput>
}

export type GalleryTextBlockOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  post?: Prisma.GalleryPostOrderByWithRelationInput
  _relevance?: Prisma.GalleryTextBlockOrderByRelevanceInput
}

export type GalleryTextBlockWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.GalleryTextBlockWhereInput | Prisma.GalleryTextBlockWhereInput[]
  OR?: Prisma.GalleryTextBlockWhereInput[]
  NOT?: Prisma.GalleryTextBlockWhereInput | Prisma.GalleryTextBlockWhereInput[]
  postId?: Prisma.IntFilter<"GalleryTextBlock"> | number
  content?: Prisma.StringFilter<"GalleryTextBlock"> | string
  order?: Prisma.IntFilter<"GalleryTextBlock"> | number
  createdAt?: Prisma.DateTimeFilter<"GalleryTextBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GalleryTextBlock"> | Date | string
  post?: Prisma.XOR<Prisma.GalleryPostScalarRelationFilter, Prisma.GalleryPostWhereInput>
}, "id">

export type GalleryTextBlockOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GalleryTextBlockCountOrderByAggregateInput
  _avg?: Prisma.GalleryTextBlockAvgOrderByAggregateInput
  _max?: Prisma.GalleryTextBlockMaxOrderByAggregateInput
  _min?: Prisma.GalleryTextBlockMinOrderByAggregateInput
  _sum?: Prisma.GalleryTextBlockSumOrderByAggregateInput
}

export type GalleryTextBlockScalarWhereWithAggregatesInput = {
  AND?: Prisma.GalleryTextBlockScalarWhereWithAggregatesInput | Prisma.GalleryTextBlockScalarWhereWithAggregatesInput[]
  OR?: Prisma.GalleryTextBlockScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GalleryTextBlockScalarWhereWithAggregatesInput | Prisma.GalleryTextBlockScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"GalleryTextBlock"> | number
  postId?: Prisma.IntWithAggregatesFilter<"GalleryTextBlock"> | number
  content?: Prisma.StringWithAggregatesFilter<"GalleryTextBlock"> | string
  order?: Prisma.IntWithAggregatesFilter<"GalleryTextBlock"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GalleryTextBlock"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GalleryTextBlock"> | Date | string
}

export type GalleryTextBlockCreateInput = {
  content: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
  post: Prisma.GalleryPostCreateNestedOneWithoutTextBlocksInput
}

export type GalleryTextBlockUncheckedCreateInput = {
  id?: number
  postId: number
  content: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GalleryTextBlockUpdateInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  post?: Prisma.GalleryPostUpdateOneRequiredWithoutTextBlocksNestedInput
}

export type GalleryTextBlockUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  postId?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryTextBlockCreateManyInput = {
  id?: number
  postId: number
  content: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GalleryTextBlockUpdateManyMutationInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryTextBlockUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  postId?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryTextBlockListRelationFilter = {
  every?: Prisma.GalleryTextBlockWhereInput
  some?: Prisma.GalleryTextBlockWhereInput
  none?: Prisma.GalleryTextBlockWhereInput
}

export type GalleryTextBlockOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GalleryTextBlockOrderByRelevanceInput = {
  fields: Prisma.GalleryTextBlockOrderByRelevanceFieldEnum | Prisma.GalleryTextBlockOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type GalleryTextBlockCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GalleryTextBlockAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type GalleryTextBlockMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GalleryTextBlockMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GalleryTextBlockSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type GalleryTextBlockCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.GalleryTextBlockCreateWithoutPostInput, Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput> | Prisma.GalleryTextBlockCreateWithoutPostInput[] | Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput | Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.GalleryTextBlockCreateManyPostInputEnvelope
  connect?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
}

export type GalleryTextBlockUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.GalleryTextBlockCreateWithoutPostInput, Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput> | Prisma.GalleryTextBlockCreateWithoutPostInput[] | Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput | Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.GalleryTextBlockCreateManyPostInputEnvelope
  connect?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
}

export type GalleryTextBlockUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryTextBlockCreateWithoutPostInput, Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput> | Prisma.GalleryTextBlockCreateWithoutPostInput[] | Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput | Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.GalleryTextBlockUpsertWithWhereUniqueWithoutPostInput | Prisma.GalleryTextBlockUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.GalleryTextBlockCreateManyPostInputEnvelope
  set?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  disconnect?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  delete?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  connect?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  update?: Prisma.GalleryTextBlockUpdateWithWhereUniqueWithoutPostInput | Prisma.GalleryTextBlockUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.GalleryTextBlockUpdateManyWithWhereWithoutPostInput | Prisma.GalleryTextBlockUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.GalleryTextBlockScalarWhereInput | Prisma.GalleryTextBlockScalarWhereInput[]
}

export type GalleryTextBlockUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryTextBlockCreateWithoutPostInput, Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput> | Prisma.GalleryTextBlockCreateWithoutPostInput[] | Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput | Prisma.GalleryTextBlockCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.GalleryTextBlockUpsertWithWhereUniqueWithoutPostInput | Prisma.GalleryTextBlockUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.GalleryTextBlockCreateManyPostInputEnvelope
  set?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  disconnect?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  delete?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  connect?: Prisma.GalleryTextBlockWhereUniqueInput | Prisma.GalleryTextBlockWhereUniqueInput[]
  update?: Prisma.GalleryTextBlockUpdateWithWhereUniqueWithoutPostInput | Prisma.GalleryTextBlockUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.GalleryTextBlockUpdateManyWithWhereWithoutPostInput | Prisma.GalleryTextBlockUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.GalleryTextBlockScalarWhereInput | Prisma.GalleryTextBlockScalarWhereInput[]
}

export type GalleryTextBlockCreateWithoutPostInput = {
  content: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GalleryTextBlockUncheckedCreateWithoutPostInput = {
  id?: number
  content: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GalleryTextBlockCreateOrConnectWithoutPostInput = {
  where: Prisma.GalleryTextBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.GalleryTextBlockCreateWithoutPostInput, Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput>
}

export type GalleryTextBlockCreateManyPostInputEnvelope = {
  data: Prisma.GalleryTextBlockCreateManyPostInput | Prisma.GalleryTextBlockCreateManyPostInput[]
  skipDuplicates?: boolean
}

export type GalleryTextBlockUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.GalleryTextBlockWhereUniqueInput
  update: Prisma.XOR<Prisma.GalleryTextBlockUpdateWithoutPostInput, Prisma.GalleryTextBlockUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.GalleryTextBlockCreateWithoutPostInput, Prisma.GalleryTextBlockUncheckedCreateWithoutPostInput>
}

export type GalleryTextBlockUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.GalleryTextBlockWhereUniqueInput
  data: Prisma.XOR<Prisma.GalleryTextBlockUpdateWithoutPostInput, Prisma.GalleryTextBlockUncheckedUpdateWithoutPostInput>
}

export type GalleryTextBlockUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.GalleryTextBlockScalarWhereInput
  data: Prisma.XOR<Prisma.GalleryTextBlockUpdateManyMutationInput, Prisma.GalleryTextBlockUncheckedUpdateManyWithoutPostInput>
}

export type GalleryTextBlockScalarWhereInput = {
  AND?: Prisma.GalleryTextBlockScalarWhereInput | Prisma.GalleryTextBlockScalarWhereInput[]
  OR?: Prisma.GalleryTextBlockScalarWhereInput[]
  NOT?: Prisma.GalleryTextBlockScalarWhereInput | Prisma.GalleryTextBlockScalarWhereInput[]
  id?: Prisma.IntFilter<"GalleryTextBlock"> | number
  postId?: Prisma.IntFilter<"GalleryTextBlock"> | number
  content?: Prisma.StringFilter<"GalleryTextBlock"> | string
  order?: Prisma.IntFilter<"GalleryTextBlock"> | number
  createdAt?: Prisma.DateTimeFilter<"GalleryTextBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GalleryTextBlock"> | Date | string
}

export type GalleryTextBlockCreateManyPostInput = {
  id?: number
  content: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GalleryTextBlockUpdateWithoutPostInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryTextBlockUncheckedUpdateWithoutPostInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryTextBlockUncheckedUpdateManyWithoutPostInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GalleryTextBlockSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postId?: boolean
  content?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  post?: boolean | Prisma.GalleryPostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryTextBlock"]>



export type GalleryTextBlockSelectScalar = {
  id?: boolean
  postId?: boolean
  content?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GalleryTextBlockOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "postId" | "content" | "order" | "createdAt" | "updatedAt", ExtArgs["result"]["galleryTextBlock"]>
export type GalleryTextBlockInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.GalleryPostDefaultArgs<ExtArgs>
}

export type $GalleryTextBlockPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GalleryTextBlock"
  objects: {
    post: Prisma.$GalleryPostPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    postId: number
    content: string
    order: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["galleryTextBlock"]>
  composites: {}
}

export type GalleryTextBlockGetPayload<S extends boolean | null | undefined | GalleryTextBlockDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload, S>

export type GalleryTextBlockCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GalleryTextBlockFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GalleryTextBlockCountAggregateInputType | true
  }

export interface GalleryTextBlockDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GalleryTextBlock'], meta: { name: 'GalleryTextBlock' } }
  /**
   * Find zero or one GalleryTextBlock that matches the filter.
   * @param {GalleryTextBlockFindUniqueArgs} args - Arguments to find a GalleryTextBlock
   * @example
   * // Get one GalleryTextBlock
   * const galleryTextBlock = await prisma.galleryTextBlock.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GalleryTextBlockFindUniqueArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GalleryTextBlock that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GalleryTextBlockFindUniqueOrThrowArgs} args - Arguments to find a GalleryTextBlock
   * @example
   * // Get one GalleryTextBlock
   * const galleryTextBlock = await prisma.galleryTextBlock.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GalleryTextBlockFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GalleryTextBlock that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockFindFirstArgs} args - Arguments to find a GalleryTextBlock
   * @example
   * // Get one GalleryTextBlock
   * const galleryTextBlock = await prisma.galleryTextBlock.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GalleryTextBlockFindFirstArgs>(args?: Prisma.SelectSubset<T, GalleryTextBlockFindFirstArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GalleryTextBlock that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockFindFirstOrThrowArgs} args - Arguments to find a GalleryTextBlock
   * @example
   * // Get one GalleryTextBlock
   * const galleryTextBlock = await prisma.galleryTextBlock.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GalleryTextBlockFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GalleryTextBlockFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GalleryTextBlocks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GalleryTextBlocks
   * const galleryTextBlocks = await prisma.galleryTextBlock.findMany()
   * 
   * // Get first 10 GalleryTextBlocks
   * const galleryTextBlocks = await prisma.galleryTextBlock.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const galleryTextBlockWithIdOnly = await prisma.galleryTextBlock.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GalleryTextBlockFindManyArgs>(args?: Prisma.SelectSubset<T, GalleryTextBlockFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GalleryTextBlock.
   * @param {GalleryTextBlockCreateArgs} args - Arguments to create a GalleryTextBlock.
   * @example
   * // Create one GalleryTextBlock
   * const GalleryTextBlock = await prisma.galleryTextBlock.create({
   *   data: {
   *     // ... data to create a GalleryTextBlock
   *   }
   * })
   * 
   */
  create<T extends GalleryTextBlockCreateArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockCreateArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GalleryTextBlocks.
   * @param {GalleryTextBlockCreateManyArgs} args - Arguments to create many GalleryTextBlocks.
   * @example
   * // Create many GalleryTextBlocks
   * const galleryTextBlock = await prisma.galleryTextBlock.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GalleryTextBlockCreateManyArgs>(args?: Prisma.SelectSubset<T, GalleryTextBlockCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a GalleryTextBlock.
   * @param {GalleryTextBlockDeleteArgs} args - Arguments to delete one GalleryTextBlock.
   * @example
   * // Delete one GalleryTextBlock
   * const GalleryTextBlock = await prisma.galleryTextBlock.delete({
   *   where: {
   *     // ... filter to delete one GalleryTextBlock
   *   }
   * })
   * 
   */
  delete<T extends GalleryTextBlockDeleteArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockDeleteArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GalleryTextBlock.
   * @param {GalleryTextBlockUpdateArgs} args - Arguments to update one GalleryTextBlock.
   * @example
   * // Update one GalleryTextBlock
   * const galleryTextBlock = await prisma.galleryTextBlock.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GalleryTextBlockUpdateArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockUpdateArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GalleryTextBlocks.
   * @param {GalleryTextBlockDeleteManyArgs} args - Arguments to filter GalleryTextBlocks to delete.
   * @example
   * // Delete a few GalleryTextBlocks
   * const { count } = await prisma.galleryTextBlock.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GalleryTextBlockDeleteManyArgs>(args?: Prisma.SelectSubset<T, GalleryTextBlockDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GalleryTextBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GalleryTextBlocks
   * const galleryTextBlock = await prisma.galleryTextBlock.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GalleryTextBlockUpdateManyArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one GalleryTextBlock.
   * @param {GalleryTextBlockUpsertArgs} args - Arguments to update or create a GalleryTextBlock.
   * @example
   * // Update or create a GalleryTextBlock
   * const galleryTextBlock = await prisma.galleryTextBlock.upsert({
   *   create: {
   *     // ... data to create a GalleryTextBlock
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GalleryTextBlock we want to update
   *   }
   * })
   */
  upsert<T extends GalleryTextBlockUpsertArgs>(args: Prisma.SelectSubset<T, GalleryTextBlockUpsertArgs<ExtArgs>>): Prisma.Prisma__GalleryTextBlockClient<runtime.Types.Result.GetResult<Prisma.$GalleryTextBlockPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GalleryTextBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockCountArgs} args - Arguments to filter GalleryTextBlocks to count.
   * @example
   * // Count the number of GalleryTextBlocks
   * const count = await prisma.galleryTextBlock.count({
   *   where: {
   *     // ... the filter for the GalleryTextBlocks we want to count
   *   }
   * })
  **/
  count<T extends GalleryTextBlockCountArgs>(
    args?: Prisma.Subset<T, GalleryTextBlockCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GalleryTextBlockCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GalleryTextBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GalleryTextBlockAggregateArgs>(args: Prisma.Subset<T, GalleryTextBlockAggregateArgs>): Prisma.PrismaPromise<GetGalleryTextBlockAggregateType<T>>

  /**
   * Group by GalleryTextBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryTextBlockGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GalleryTextBlockGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GalleryTextBlockGroupByArgs['orderBy'] }
      : { orderBy?: GalleryTextBlockGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GalleryTextBlockGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGalleryTextBlockGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GalleryTextBlock model
 */
readonly fields: GalleryTextBlockFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GalleryTextBlock.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GalleryTextBlockClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  post<T extends Prisma.GalleryPostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GalleryPostDefaultArgs<ExtArgs>>): Prisma.Prisma__GalleryPostClient<runtime.Types.Result.GetResult<Prisma.$GalleryPostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GalleryTextBlock model
 */
export interface GalleryTextBlockFieldRefs {
  readonly id: Prisma.FieldRef<"GalleryTextBlock", 'Int'>
  readonly postId: Prisma.FieldRef<"GalleryTextBlock", 'Int'>
  readonly content: Prisma.FieldRef<"GalleryTextBlock", 'String'>
  readonly order: Prisma.FieldRef<"GalleryTextBlock", 'Int'>
  readonly createdAt: Prisma.FieldRef<"GalleryTextBlock", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GalleryTextBlock", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GalleryTextBlock findUnique
 */
export type GalleryTextBlockFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * Filter, which GalleryTextBlock to fetch.
   */
  where: Prisma.GalleryTextBlockWhereUniqueInput
}

/**
 * GalleryTextBlock findUniqueOrThrow
 */
export type GalleryTextBlockFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * Filter, which GalleryTextBlock to fetch.
   */
  where: Prisma.GalleryTextBlockWhereUniqueInput
}

/**
 * GalleryTextBlock findFirst
 */
export type GalleryTextBlockFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * Filter, which GalleryTextBlock to fetch.
   */
  where?: Prisma.GalleryTextBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryTextBlocks to fetch.
   */
  orderBy?: Prisma.GalleryTextBlockOrderByWithRelationInput | Prisma.GalleryTextBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GalleryTextBlocks.
   */
  cursor?: Prisma.GalleryTextBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryTextBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryTextBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GalleryTextBlocks.
   */
  distinct?: Prisma.GalleryTextBlockScalarFieldEnum | Prisma.GalleryTextBlockScalarFieldEnum[]
}

/**
 * GalleryTextBlock findFirstOrThrow
 */
export type GalleryTextBlockFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * Filter, which GalleryTextBlock to fetch.
   */
  where?: Prisma.GalleryTextBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryTextBlocks to fetch.
   */
  orderBy?: Prisma.GalleryTextBlockOrderByWithRelationInput | Prisma.GalleryTextBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GalleryTextBlocks.
   */
  cursor?: Prisma.GalleryTextBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryTextBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryTextBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GalleryTextBlocks.
   */
  distinct?: Prisma.GalleryTextBlockScalarFieldEnum | Prisma.GalleryTextBlockScalarFieldEnum[]
}

/**
 * GalleryTextBlock findMany
 */
export type GalleryTextBlockFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * Filter, which GalleryTextBlocks to fetch.
   */
  where?: Prisma.GalleryTextBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryTextBlocks to fetch.
   */
  orderBy?: Prisma.GalleryTextBlockOrderByWithRelationInput | Prisma.GalleryTextBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GalleryTextBlocks.
   */
  cursor?: Prisma.GalleryTextBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryTextBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryTextBlocks.
   */
  skip?: number
  distinct?: Prisma.GalleryTextBlockScalarFieldEnum | Prisma.GalleryTextBlockScalarFieldEnum[]
}

/**
 * GalleryTextBlock create
 */
export type GalleryTextBlockCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * The data needed to create a GalleryTextBlock.
   */
  data: Prisma.XOR<Prisma.GalleryTextBlockCreateInput, Prisma.GalleryTextBlockUncheckedCreateInput>
}

/**
 * GalleryTextBlock createMany
 */
export type GalleryTextBlockCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GalleryTextBlocks.
   */
  data: Prisma.GalleryTextBlockCreateManyInput | Prisma.GalleryTextBlockCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GalleryTextBlock update
 */
export type GalleryTextBlockUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * The data needed to update a GalleryTextBlock.
   */
  data: Prisma.XOR<Prisma.GalleryTextBlockUpdateInput, Prisma.GalleryTextBlockUncheckedUpdateInput>
  /**
   * Choose, which GalleryTextBlock to update.
   */
  where: Prisma.GalleryTextBlockWhereUniqueInput
}

/**
 * GalleryTextBlock updateMany
 */
export type GalleryTextBlockUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GalleryTextBlocks.
   */
  data: Prisma.XOR<Prisma.GalleryTextBlockUpdateManyMutationInput, Prisma.GalleryTextBlockUncheckedUpdateManyInput>
  /**
   * Filter which GalleryTextBlocks to update
   */
  where?: Prisma.GalleryTextBlockWhereInput
  /**
   * Limit how many GalleryTextBlocks to update.
   */
  limit?: number
}

/**
 * GalleryTextBlock upsert
 */
export type GalleryTextBlockUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * The filter to search for the GalleryTextBlock to update in case it exists.
   */
  where: Prisma.GalleryTextBlockWhereUniqueInput
  /**
   * In case the GalleryTextBlock found by the `where` argument doesn't exist, create a new GalleryTextBlock with this data.
   */
  create: Prisma.XOR<Prisma.GalleryTextBlockCreateInput, Prisma.GalleryTextBlockUncheckedCreateInput>
  /**
   * In case the GalleryTextBlock was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GalleryTextBlockUpdateInput, Prisma.GalleryTextBlockUncheckedUpdateInput>
}

/**
 * GalleryTextBlock delete
 */
export type GalleryTextBlockDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
  /**
   * Filter which GalleryTextBlock to delete.
   */
  where: Prisma.GalleryTextBlockWhereUniqueInput
}

/**
 * GalleryTextBlock deleteMany
 */
export type GalleryTextBlockDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GalleryTextBlocks to delete
   */
  where?: Prisma.GalleryTextBlockWhereInput
  /**
   * Limit how many GalleryTextBlocks to delete.
   */
  limit?: number
}

/**
 * GalleryTextBlock without action
 */
export type GalleryTextBlockDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryTextBlock
   */
  select?: Prisma.GalleryTextBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryTextBlock
   */
  omit?: Prisma.GalleryTextBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryTextBlockInclude<ExtArgs> | null
}
