
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorshipVideo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorshipVideo
 * 
 */
export type WorshipVideoModel = runtime.Types.Result.DefaultSelection<Prisma.$WorshipVideoPayload>

export type AggregateWorshipVideo = {
  _count: WorshipVideoCountAggregateOutputType | null
  _avg: WorshipVideoAvgAggregateOutputType | null
  _sum: WorshipVideoSumAggregateOutputType | null
  _min: WorshipVideoMinAggregateOutputType | null
  _max: WorshipVideoMaxAggregateOutputType | null
}

export type WorshipVideoAvgAggregateOutputType = {
  id: number | null
  order: number | null
}

export type WorshipVideoSumAggregateOutputType = {
  id: number | null
  order: number | null
}

export type WorshipVideoMinAggregateOutputType = {
  id: number | null
  category: string | null
  videoUrl: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorshipVideoMaxAggregateOutputType = {
  id: number | null
  category: string | null
  videoUrl: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorshipVideoCountAggregateOutputType = {
  id: number
  category: number
  videoUrl: number
  order: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type WorshipVideoAvgAggregateInputType = {
  id?: true
  order?: true
}

export type WorshipVideoSumAggregateInputType = {
  id?: true
  order?: true
}

export type WorshipVideoMinAggregateInputType = {
  id?: true
  category?: true
  videoUrl?: true
  order?: true
  createdAt?: true
  updatedAt?: true
}

export type WorshipVideoMaxAggregateInputType = {
  id?: true
  category?: true
  videoUrl?: true
  order?: true
  createdAt?: true
  updatedAt?: true
}

export type WorshipVideoCountAggregateInputType = {
  id?: true
  category?: true
  videoUrl?: true
  order?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WorshipVideoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorshipVideo to aggregate.
   */
  where?: Prisma.WorshipVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorshipVideos to fetch.
   */
  orderBy?: Prisma.WorshipVideoOrderByWithRelationInput | Prisma.WorshipVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorshipVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorshipVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorshipVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorshipVideos
  **/
  _count?: true | WorshipVideoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorshipVideoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorshipVideoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorshipVideoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorshipVideoMaxAggregateInputType
}

export type GetWorshipVideoAggregateType<T extends WorshipVideoAggregateArgs> = {
      [P in keyof T & keyof AggregateWorshipVideo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorshipVideo[P]>
    : Prisma.GetScalarType<T[P], AggregateWorshipVideo[P]>
}




export type WorshipVideoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorshipVideoWhereInput
  orderBy?: Prisma.WorshipVideoOrderByWithAggregationInput | Prisma.WorshipVideoOrderByWithAggregationInput[]
  by: Prisma.WorshipVideoScalarFieldEnum[] | Prisma.WorshipVideoScalarFieldEnum
  having?: Prisma.WorshipVideoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorshipVideoCountAggregateInputType | true
  _avg?: WorshipVideoAvgAggregateInputType
  _sum?: WorshipVideoSumAggregateInputType
  _min?: WorshipVideoMinAggregateInputType
  _max?: WorshipVideoMaxAggregateInputType
}

export type WorshipVideoGroupByOutputType = {
  id: number
  category: string
  videoUrl: string
  order: number
  createdAt: Date
  updatedAt: Date
  _count: WorshipVideoCountAggregateOutputType | null
  _avg: WorshipVideoAvgAggregateOutputType | null
  _sum: WorshipVideoSumAggregateOutputType | null
  _min: WorshipVideoMinAggregateOutputType | null
  _max: WorshipVideoMaxAggregateOutputType | null
}

type GetWorshipVideoGroupByPayload<T extends WorshipVideoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorshipVideoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorshipVideoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorshipVideoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorshipVideoGroupByOutputType[P]>
      }
    >
  >



export type WorshipVideoWhereInput = {
  AND?: Prisma.WorshipVideoWhereInput | Prisma.WorshipVideoWhereInput[]
  OR?: Prisma.WorshipVideoWhereInput[]
  NOT?: Prisma.WorshipVideoWhereInput | Prisma.WorshipVideoWhereInput[]
  id?: Prisma.IntFilter<"WorshipVideo"> | number
  category?: Prisma.StringFilter<"WorshipVideo"> | string
  videoUrl?: Prisma.StringFilter<"WorshipVideo"> | string
  order?: Prisma.IntFilter<"WorshipVideo"> | number
  createdAt?: Prisma.DateTimeFilter<"WorshipVideo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorshipVideo"> | Date | string
}

export type WorshipVideoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  category?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.WorshipVideoOrderByRelevanceInput
}

export type WorshipVideoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  category_order?: Prisma.WorshipVideoCategoryOrderCompoundUniqueInput
  AND?: Prisma.WorshipVideoWhereInput | Prisma.WorshipVideoWhereInput[]
  OR?: Prisma.WorshipVideoWhereInput[]
  NOT?: Prisma.WorshipVideoWhereInput | Prisma.WorshipVideoWhereInput[]
  category?: Prisma.StringFilter<"WorshipVideo"> | string
  videoUrl?: Prisma.StringFilter<"WorshipVideo"> | string
  order?: Prisma.IntFilter<"WorshipVideo"> | number
  createdAt?: Prisma.DateTimeFilter<"WorshipVideo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorshipVideo"> | Date | string
}, "id" | "category_order">

export type WorshipVideoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  category?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WorshipVideoCountOrderByAggregateInput
  _avg?: Prisma.WorshipVideoAvgOrderByAggregateInput
  _max?: Prisma.WorshipVideoMaxOrderByAggregateInput
  _min?: Prisma.WorshipVideoMinOrderByAggregateInput
  _sum?: Prisma.WorshipVideoSumOrderByAggregateInput
}

export type WorshipVideoScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorshipVideoScalarWhereWithAggregatesInput | Prisma.WorshipVideoScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorshipVideoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorshipVideoScalarWhereWithAggregatesInput | Prisma.WorshipVideoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"WorshipVideo"> | number
  category?: Prisma.StringWithAggregatesFilter<"WorshipVideo"> | string
  videoUrl?: Prisma.StringWithAggregatesFilter<"WorshipVideo"> | string
  order?: Prisma.IntWithAggregatesFilter<"WorshipVideo"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorshipVideo"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorshipVideo"> | Date | string
}

export type WorshipVideoCreateInput = {
  category: string
  videoUrl: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorshipVideoUncheckedCreateInput = {
  id?: number
  category: string
  videoUrl: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorshipVideoUpdateInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorshipVideoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorshipVideoCreateManyInput = {
  id?: number
  category: string
  videoUrl: string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorshipVideoUpdateManyMutationInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorshipVideoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorshipVideoOrderByRelevanceInput = {
  fields: Prisma.WorshipVideoOrderByRelevanceFieldEnum | Prisma.WorshipVideoOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type WorshipVideoCategoryOrderCompoundUniqueInput = {
  category: string
  order: number
}

export type WorshipVideoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorshipVideoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type WorshipVideoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorshipVideoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorshipVideoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
}



export type WorshipVideoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  category?: boolean
  videoUrl?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["worshipVideo"]>



export type WorshipVideoSelectScalar = {
  id?: boolean
  category?: boolean
  videoUrl?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WorshipVideoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "category" | "videoUrl" | "order" | "createdAt" | "updatedAt", ExtArgs["result"]["worshipVideo"]>

export type $WorshipVideoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorshipVideo"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    category: string
    videoUrl: string
    order: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["worshipVideo"]>
  composites: {}
}

export type WorshipVideoGetPayload<S extends boolean | null | undefined | WorshipVideoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload, S>

export type WorshipVideoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorshipVideoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorshipVideoCountAggregateInputType | true
  }

export interface WorshipVideoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorshipVideo'], meta: { name: 'WorshipVideo' } }
  /**
   * Find zero or one WorshipVideo that matches the filter.
   * @param {WorshipVideoFindUniqueArgs} args - Arguments to find a WorshipVideo
   * @example
   * // Get one WorshipVideo
   * const worshipVideo = await prisma.worshipVideo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorshipVideoFindUniqueArgs>(args: Prisma.SelectSubset<T, WorshipVideoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorshipVideo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorshipVideoFindUniqueOrThrowArgs} args - Arguments to find a WorshipVideo
   * @example
   * // Get one WorshipVideo
   * const worshipVideo = await prisma.worshipVideo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorshipVideoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorshipVideoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorshipVideo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoFindFirstArgs} args - Arguments to find a WorshipVideo
   * @example
   * // Get one WorshipVideo
   * const worshipVideo = await prisma.worshipVideo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorshipVideoFindFirstArgs>(args?: Prisma.SelectSubset<T, WorshipVideoFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorshipVideo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoFindFirstOrThrowArgs} args - Arguments to find a WorshipVideo
   * @example
   * // Get one WorshipVideo
   * const worshipVideo = await prisma.worshipVideo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorshipVideoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorshipVideoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorshipVideos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorshipVideos
   * const worshipVideos = await prisma.worshipVideo.findMany()
   * 
   * // Get first 10 WorshipVideos
   * const worshipVideos = await prisma.worshipVideo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const worshipVideoWithIdOnly = await prisma.worshipVideo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorshipVideoFindManyArgs>(args?: Prisma.SelectSubset<T, WorshipVideoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorshipVideo.
   * @param {WorshipVideoCreateArgs} args - Arguments to create a WorshipVideo.
   * @example
   * // Create one WorshipVideo
   * const WorshipVideo = await prisma.worshipVideo.create({
   *   data: {
   *     // ... data to create a WorshipVideo
   *   }
   * })
   * 
   */
  create<T extends WorshipVideoCreateArgs>(args: Prisma.SelectSubset<T, WorshipVideoCreateArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorshipVideos.
   * @param {WorshipVideoCreateManyArgs} args - Arguments to create many WorshipVideos.
   * @example
   * // Create many WorshipVideos
   * const worshipVideo = await prisma.worshipVideo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorshipVideoCreateManyArgs>(args?: Prisma.SelectSubset<T, WorshipVideoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a WorshipVideo.
   * @param {WorshipVideoDeleteArgs} args - Arguments to delete one WorshipVideo.
   * @example
   * // Delete one WorshipVideo
   * const WorshipVideo = await prisma.worshipVideo.delete({
   *   where: {
   *     // ... filter to delete one WorshipVideo
   *   }
   * })
   * 
   */
  delete<T extends WorshipVideoDeleteArgs>(args: Prisma.SelectSubset<T, WorshipVideoDeleteArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorshipVideo.
   * @param {WorshipVideoUpdateArgs} args - Arguments to update one WorshipVideo.
   * @example
   * // Update one WorshipVideo
   * const worshipVideo = await prisma.worshipVideo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorshipVideoUpdateArgs>(args: Prisma.SelectSubset<T, WorshipVideoUpdateArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorshipVideos.
   * @param {WorshipVideoDeleteManyArgs} args - Arguments to filter WorshipVideos to delete.
   * @example
   * // Delete a few WorshipVideos
   * const { count } = await prisma.worshipVideo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorshipVideoDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorshipVideoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorshipVideos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorshipVideos
   * const worshipVideo = await prisma.worshipVideo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorshipVideoUpdateManyArgs>(args: Prisma.SelectSubset<T, WorshipVideoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one WorshipVideo.
   * @param {WorshipVideoUpsertArgs} args - Arguments to update or create a WorshipVideo.
   * @example
   * // Update or create a WorshipVideo
   * const worshipVideo = await prisma.worshipVideo.upsert({
   *   create: {
   *     // ... data to create a WorshipVideo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorshipVideo we want to update
   *   }
   * })
   */
  upsert<T extends WorshipVideoUpsertArgs>(args: Prisma.SelectSubset<T, WorshipVideoUpsertArgs<ExtArgs>>): Prisma.Prisma__WorshipVideoClient<runtime.Types.Result.GetResult<Prisma.$WorshipVideoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorshipVideos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoCountArgs} args - Arguments to filter WorshipVideos to count.
   * @example
   * // Count the number of WorshipVideos
   * const count = await prisma.worshipVideo.count({
   *   where: {
   *     // ... the filter for the WorshipVideos we want to count
   *   }
   * })
  **/
  count<T extends WorshipVideoCountArgs>(
    args?: Prisma.Subset<T, WorshipVideoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorshipVideoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorshipVideo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorshipVideoAggregateArgs>(args: Prisma.Subset<T, WorshipVideoAggregateArgs>): Prisma.PrismaPromise<GetWorshipVideoAggregateType<T>>

  /**
   * Group by WorshipVideo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorshipVideoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorshipVideoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorshipVideoGroupByArgs['orderBy'] }
      : { orderBy?: WorshipVideoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorshipVideoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorshipVideoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorshipVideo model
 */
readonly fields: WorshipVideoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorshipVideo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorshipVideoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorshipVideo model
 */
export interface WorshipVideoFieldRefs {
  readonly id: Prisma.FieldRef<"WorshipVideo", 'Int'>
  readonly category: Prisma.FieldRef<"WorshipVideo", 'String'>
  readonly videoUrl: Prisma.FieldRef<"WorshipVideo", 'String'>
  readonly order: Prisma.FieldRef<"WorshipVideo", 'Int'>
  readonly createdAt: Prisma.FieldRef<"WorshipVideo", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorshipVideo", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorshipVideo findUnique
 */
export type WorshipVideoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * Filter, which WorshipVideo to fetch.
   */
  where: Prisma.WorshipVideoWhereUniqueInput
}

/**
 * WorshipVideo findUniqueOrThrow
 */
export type WorshipVideoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * Filter, which WorshipVideo to fetch.
   */
  where: Prisma.WorshipVideoWhereUniqueInput
}

/**
 * WorshipVideo findFirst
 */
export type WorshipVideoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * Filter, which WorshipVideo to fetch.
   */
  where?: Prisma.WorshipVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorshipVideos to fetch.
   */
  orderBy?: Prisma.WorshipVideoOrderByWithRelationInput | Prisma.WorshipVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorshipVideos.
   */
  cursor?: Prisma.WorshipVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorshipVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorshipVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorshipVideos.
   */
  distinct?: Prisma.WorshipVideoScalarFieldEnum | Prisma.WorshipVideoScalarFieldEnum[]
}

/**
 * WorshipVideo findFirstOrThrow
 */
export type WorshipVideoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * Filter, which WorshipVideo to fetch.
   */
  where?: Prisma.WorshipVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorshipVideos to fetch.
   */
  orderBy?: Prisma.WorshipVideoOrderByWithRelationInput | Prisma.WorshipVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorshipVideos.
   */
  cursor?: Prisma.WorshipVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorshipVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorshipVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorshipVideos.
   */
  distinct?: Prisma.WorshipVideoScalarFieldEnum | Prisma.WorshipVideoScalarFieldEnum[]
}

/**
 * WorshipVideo findMany
 */
export type WorshipVideoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * Filter, which WorshipVideos to fetch.
   */
  where?: Prisma.WorshipVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorshipVideos to fetch.
   */
  orderBy?: Prisma.WorshipVideoOrderByWithRelationInput | Prisma.WorshipVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorshipVideos.
   */
  cursor?: Prisma.WorshipVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorshipVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorshipVideos.
   */
  skip?: number
  distinct?: Prisma.WorshipVideoScalarFieldEnum | Prisma.WorshipVideoScalarFieldEnum[]
}

/**
 * WorshipVideo create
 */
export type WorshipVideoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * The data needed to create a WorshipVideo.
   */
  data: Prisma.XOR<Prisma.WorshipVideoCreateInput, Prisma.WorshipVideoUncheckedCreateInput>
}

/**
 * WorshipVideo createMany
 */
export type WorshipVideoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorshipVideos.
   */
  data: Prisma.WorshipVideoCreateManyInput | Prisma.WorshipVideoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorshipVideo update
 */
export type WorshipVideoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * The data needed to update a WorshipVideo.
   */
  data: Prisma.XOR<Prisma.WorshipVideoUpdateInput, Prisma.WorshipVideoUncheckedUpdateInput>
  /**
   * Choose, which WorshipVideo to update.
   */
  where: Prisma.WorshipVideoWhereUniqueInput
}

/**
 * WorshipVideo updateMany
 */
export type WorshipVideoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorshipVideos.
   */
  data: Prisma.XOR<Prisma.WorshipVideoUpdateManyMutationInput, Prisma.WorshipVideoUncheckedUpdateManyInput>
  /**
   * Filter which WorshipVideos to update
   */
  where?: Prisma.WorshipVideoWhereInput
  /**
   * Limit how many WorshipVideos to update.
   */
  limit?: number
}

/**
 * WorshipVideo upsert
 */
export type WorshipVideoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * The filter to search for the WorshipVideo to update in case it exists.
   */
  where: Prisma.WorshipVideoWhereUniqueInput
  /**
   * In case the WorshipVideo found by the `where` argument doesn't exist, create a new WorshipVideo with this data.
   */
  create: Prisma.XOR<Prisma.WorshipVideoCreateInput, Prisma.WorshipVideoUncheckedCreateInput>
  /**
   * In case the WorshipVideo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorshipVideoUpdateInput, Prisma.WorshipVideoUncheckedUpdateInput>
}

/**
 * WorshipVideo delete
 */
export type WorshipVideoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
  /**
   * Filter which WorshipVideo to delete.
   */
  where: Prisma.WorshipVideoWhereUniqueInput
}

/**
 * WorshipVideo deleteMany
 */
export type WorshipVideoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorshipVideos to delete
   */
  where?: Prisma.WorshipVideoWhereInput
  /**
   * Limit how many WorshipVideos to delete.
   */
  limit?: number
}

/**
 * WorshipVideo without action
 */
export type WorshipVideoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorshipVideo
   */
  select?: Prisma.WorshipVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorshipVideo
   */
  omit?: Prisma.WorshipVideoOmit<ExtArgs> | null
}
