
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Announcement: 'Announcement',
  GalleryPost: 'GalleryPost',
  GalleryImage: 'GalleryImage',
  GalleryTextBlock: 'GalleryTextBlock',
  WorshipVideo: 'WorshipVideo'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  userPassword: 'userPassword',
  userName: 'userName',
  userPhone: 'userPhone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  isImportant: 'isImportant',
  viewCount: 'viewCount',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AnnouncementScalarFieldEnum = (typeof AnnouncementScalarFieldEnum)[keyof typeof AnnouncementScalarFieldEnum]


export const GalleryPostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GalleryPostScalarFieldEnum = (typeof GalleryPostScalarFieldEnum)[keyof typeof GalleryPostScalarFieldEnum]


export const GalleryImageScalarFieldEnum = {
  id: 'id',
  fileKey: 'fileKey',
  postId: 'postId',
  order: 'order',
  aspectRatio: 'aspectRatio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GalleryImageScalarFieldEnum = (typeof GalleryImageScalarFieldEnum)[keyof typeof GalleryImageScalarFieldEnum]


export const GalleryTextBlockScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  content: 'content',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GalleryTextBlockScalarFieldEnum = (typeof GalleryTextBlockScalarFieldEnum)[keyof typeof GalleryTextBlockScalarFieldEnum]


export const WorshipVideoScalarFieldEnum = {
  id: 'id',
  category: 'category',
  videoUrl: 'videoUrl',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorshipVideoScalarFieldEnum = (typeof WorshipVideoScalarFieldEnum)[keyof typeof WorshipVideoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UserOrderByRelevanceFieldEnum = {
  userId: 'userId',
  userPassword: 'userPassword',
  userName: 'userName',
  userPhone: 'userPhone'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const AnnouncementOrderByRelevanceFieldEnum = {
  title: 'title',
  content: 'content'
} as const

export type AnnouncementOrderByRelevanceFieldEnum = (typeof AnnouncementOrderByRelevanceFieldEnum)[keyof typeof AnnouncementOrderByRelevanceFieldEnum]


export const GalleryPostOrderByRelevanceFieldEnum = {
  title: 'title',
  content: 'content'
} as const

export type GalleryPostOrderByRelevanceFieldEnum = (typeof GalleryPostOrderByRelevanceFieldEnum)[keyof typeof GalleryPostOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const GalleryImageOrderByRelevanceFieldEnum = {
  fileKey: 'fileKey'
} as const

export type GalleryImageOrderByRelevanceFieldEnum = (typeof GalleryImageOrderByRelevanceFieldEnum)[keyof typeof GalleryImageOrderByRelevanceFieldEnum]


export const GalleryTextBlockOrderByRelevanceFieldEnum = {
  content: 'content'
} as const

export type GalleryTextBlockOrderByRelevanceFieldEnum = (typeof GalleryTextBlockOrderByRelevanceFieldEnum)[keyof typeof GalleryTextBlockOrderByRelevanceFieldEnum]


export const WorshipVideoOrderByRelevanceFieldEnum = {
  category: 'category',
  videoUrl: 'videoUrl'
} as const

export type WorshipVideoOrderByRelevanceFieldEnum = (typeof WorshipVideoOrderByRelevanceFieldEnum)[keyof typeof WorshipVideoOrderByRelevanceFieldEnum]

