apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jaejadle

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-jaejadle-secret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jaejadle
    newTag: main-sha-90bac3dc3667668a3e963dc6d5c4ca7d9211f1bb

patchesStrategicMerge:
  - deployment-patch.yaml
